version: "3.7"

services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432

  resources:
    build:
      context: .
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=password
      - DEBUG=true
    ports:
      - 8000:8000
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
