# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        docker-compose up -d
        docker-compose run resources sh -c './src/manage.py test ./src'
        
  publish:
    if: ${{ github.ref == 'refs/heads/master' }}
    environment: dockerhub
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags:  cajibhuk/resources-api:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
