# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install virtualenv \
        && virtualenv --python=python3 .venv \
        && set -o pipefail \
        && curl -sSL https://raw.githubusercontent.com/sdispater/poetry/0.12.16/get-poetry.py > get-poetry.py \
        && python get-poetry.py --version 0.12.16 -y \
        && . ${HOME}/.poetry/env \
        && . ./.venv/bin/activate \
        && poetry install
    - name: Test with pytest
      run: |
        docker-compose up -d postgres \
        && . ./.venv/bin/activate \
        && ./src/manage.py test ./src
